import Head from "next/head";
import { useState } from "react";
import Image from "next/image";
import styles from "@/styles/Home.module.css";


export default function Home() {
  const [name, setName] = useState("");
  const [address, setAddress] = useState("");
  const [education, setEducation] = useState("");
  const [gender, setGender] = useState("");
  const [password, setPassword] = useState("");

  const handleSubmit = async (e) => {
    e.preventDefault();
    try {
      const response = await fetch("http://localhost:8080/api/signup", {
        method: "POST",
        headers: {
          "content-type": "application/json",
        },
        body: JSON.stringify({
          name: name,
          address: address,
          education: education,
          gender: gender,
          password: password,
        }),
      }).catch((e) => {
        console.log(e);
      });
      // if (response.ok) {
      //   setSubmitted(true);
      //   console.log(response);
      //   console.log(submitted);
      // }
      return response.json();
    } catch (error) {
      console.log(error);
    }
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <form onSubmit={handleSubmit}>
          <div className={styles.flexcenter}>
            <div className={styles.form}>
              <div className={styles.formInput}>
                <label htmlFor="">
                  Name <span>*</span>
                </label>
                <input
                  type="text"
                  value={name}
                  placeholder="Full Name"
                  onChange={(e) => setName(e.target.value)}
                />
              </div>
              <div className={styles.formInput}>
                <label htmlFor="">
                  Address <span>*</span>
                </label>
                <input
                  type="text"
                  value={address}
                  placeholder="Address"
                  onChange={(e) => setAddress(e.target.value)}
                />
              </div>
              <div className={styles.formInput}>
                <label htmlFor="">
                  Gender <span>*</span>
                </label>
                <select
                  name=""
                  id=""
                  value={gender}
                  onChange={(e) => setGender(e.target.value)}
                >
                  <option value="none">Select Option</option>
                  <option value="Male">Male</option>
                  <option value="FeMale">Female</option>
                </select>
              </div>
              <div className={styles.formInput}>
                <label htmlFor="">
                  Education <span>*</span>
                </label>
                <select
                  name=""
                  value={education}
                  id=""
                  onChange={(e) => setEducation(e.target.value)}
                >
                  <option value="none">Select Option</option>
                  <option value="BE">BE</option>
                  <option value="B Arch">B Arch.</option>
                  <option value="Graduation">Graduation</option>
                  <option value="College Level">College Level</option>
                </select>
              </div>
              <div className={styles.formInput}>
                <label htmlFor="">Password</label>
                <input
                  type="text"
                  value={password}
                  placeholder="Password"
                  onChange={(e) => setPassword(e.target.value)}
                />
              </div>
              <div className={styles.submit}>
                <button type="submit">Submit</button>
              </div>
            </div>
          </div>
        </form>
      </main>
    </>
  );
}
